export const achievements = [
  {
    name: 'Pair Extraordinaire',
    tier: 'Silver',
    count: 3,
    note: 'Co-authored PRs',
    img: 'https://github.githubassets.com/assets/pair-extraordinaire-silver-a0b2b472348c.png',
    href: 'https://github.com/Saikumar-bali?achievement=pair-extraordinaire&tab=achievements',
  },
  {
    name: 'Pull Shark',
    tier: 'Silver',
    count: 3,
    note: 'Merged pull requests',
    img: 'https://github.githubassets.com/assets/pull-shark-silver-0643f87ac9fd.png',
    href: 'https://github.com/Saikumar-bali?achievement=pull-shark&tab=achievements',
  },
  {
    name: 'YOLO',
    tier: 'Default',
    count: 1,
    note: 'Merged without review',
    img: 'https://github.githubassets.com/assets/yolo-default-be0bbff04951.png',
    href: 'https://github.com/Saikumar-bali?achievement=yolo&tab=achievements',
  },
  {
    name: 'Quickdraw',
    tier: 'Default',
    count: 1,
    note: 'Closed PR in under a minute',
    img: 'https://github.githubassets.com/assets/quickdraw-default-39c6aec8ff89.png',
    href: 'https://github.com/Saikumar-bali?achievement=quickdraw&tab=achievements',
  },
]

// sheet: col/row into story-sheet.png (4×2). Agent beats use standalone img files.
// purpose = why it exists, in plain language. caption = how it works.
export const storyBeats = [
  {
    id: 'pr-autofix',
    title: 'The PR fixes itself',
    repo: 'AAGAM_E-commerce',
    workflow: 'pr-autofix.json',
    purpose: 'So small bugs get fixed before a human even opens the PR.',
    caption: 'Open a PR. An agent reads the diff, sorts real bugs from noise, fixes the safe ones, pushes, and leaves one report comment.',
    href: 'https://github.com/Saikumar-bali/AAGAM_E-commerce/tree/main/automations/pr-autofix.json',
    kind: 'agent',
    img: '/textures/automation/pr-autofix.png',
  },
  {
    id: 'judge',
    title: 'The judge bot',
    repo: 'AAGAM_E-commerce',
    workflow: 'bot-review-triage.json',
    purpose: 'So review bots do not waste your time with false alarms.',
    caption: 'CodeRabbit, Qodo, or Copilot posts findings. A second agent checks them against the real code, fixes what is true, and refutes the rest with file and line.',
    href: 'https://github.com/Saikumar-bali/AAGAM_E-commerce/tree/main/automations/bot-review-triage.json',
    kind: 'agent',
    img: '/textures/automation/judge.png',
  },
  {
    id: 'crash-issue',
    title: 'Crash becomes an issue',
    repo: 'AAGAM_E-commerce',
    workflow: 'Sentry Issue Stream',
    purpose: 'So production failures never stay invisible.',
    caption: 'Production NestJS throws. Sentry opens a GitHub issue with the stack trace and a bug label before anyone notices.',
    href: 'https://github.com/Saikumar-bali/AAGAM_E-commerce/issues?q=author%3Aapp%2Fsentry',
    kind: 'watch',
    img: '/textures/automation/crash-issue.png',
  },
  {
    id: 'push',
    title: 'The push',
    repo: 'movie_mandir',
    workflow: 'android-build.yml',
    purpose: 'So every merge produces a ready-to-install APK with no manual build step.',
    caption: 'Push to main spins up JDK 17, injects 12 secrets, runs Gradle assembleRelease, and uploads the APK artifact.',
    sheet: { col: 0, row: 0 },
    kind: 'ship',
    href: 'https://github.com/Saikumar-bali/movie_mandir/actions/workflows/android-build.yml',
  },
  {
    id: 'night-shift',
    title: 'Night shift',
    repo: 'erp_automation_bot',
    workflow: 'scheduled-attendance.yml',
    purpose: 'So attendance is marked on time even when nobody is at the desk.',
    caption: 'Cron at 7:30 AM IST, Monday to Saturday. A Windows runner boots Playwright, geofences the check-in, and uploads logs and screenshots.',
    sheet: { col: 1, row: 0 },
    kind: 'cron',
    href: 'https://github.com/Saikumar-bali/erp_automation_bot/actions/workflows/scheduled-attendance.yml',
  },
  {
    id: 'harvest',
    title: 'The harvest',
    repo: 'news_website',
    workflow: 'scrape.yml',
    purpose: 'So the news site stays fresh without anyone copying stories by hand.',
    caption: 'Hourly cron sweeps 20-plus Telugu sources, pushes results to Firebase, and auto-commits the data back to the repo.',
    sheet: { col: 2, row: 0 },
    kind: 'cron',
    href: 'https://github.com/Saikumar-bali/news_website/actions/workflows/scrape.yml',
  },
  {
    id: 'two-phones',
    title: 'Two phones, one build',
    repo: 'AAGAM_E-commerce',
    workflow: 'android-apk-release.yml',
    purpose: 'So only the apps that changed get rebuilt, and releases ship themselves.',
    caption: 'Path filters detect which apps changed, build customer and partners APKs in parallel, validate Google Sign-In, and publish a GitHub Release.',
    sheet: { col: 0, row: 1 },
    kind: 'ship',
    href: 'https://github.com/Saikumar-bali/AAGAM_E-commerce/actions/workflows/android-apk-release.yml',
  },
  {
    id: 'four-lanes',
    title: 'Four lanes green',
    repo: 'AAGAM_E-commerce',
    workflow: 'ci.yml',
    purpose: 'So broken code is caught before it can reach production.',
    caption: 'Turbo build, Prisma migrations, then four Playwright shards against live Postgres and Redis services, all gated before deploy.',
    sheet: { col: 1, row: 1 },
    kind: 'ship',
    href: 'https://github.com/Saikumar-bali/AAGAM_E-commerce/actions/workflows/ci.yml',
  },
  {
    id: 'ship-it',
    title: 'Ship it',
    repo: 'AAGAM_E-commerce',
    workflow: 'deploy.yml',
    purpose: 'So releases go out safely, and a bad deploy is caught before users feel it.',
    caption: 'After CI goes green: SSH to production, sync the exact SHA, migrate, restart, then poll the public health check up to 30 times.',
    sheet: { col: 2, row: 1 },
    kind: 'ship',
    href: 'https://github.com/Saikumar-bali/AAGAM_E-commerce/actions/workflows/deploy.yml',
  },
]

export const featuredAgents = [
  {
    id: 'pr-autofix',
    name: 'PR review + autofix',
    purpose: 'Catches bugs early so review starts from a cleaner diff.',
    line: 'Agent reads the diff, fixes real bugs, pushes to your branch, reports what it skipped.',
    href: 'https://github.com/Saikumar-bali/AAGAM_E-commerce/tree/main/automations/pr-autofix.json',
  },
  {
    id: 'judge',
    name: 'Judge bot',
    purpose: 'Keeps bot noise out of your review queue.',
    line: 'Triages CodeRabbit, Qodo, and Copilot findings against the code. Real gets fixed, false gets refuted.',
    href: 'https://github.com/Saikumar-bali/AAGAM_E-commerce/tree/main/automations/bot-review-triage.json',
  },
  {
    id: 'ux',
    name: 'UX redesign agent',
    purpose: 'Turns “this screen feels off” into a concrete draft you can accept or reject.',
    line: 'Weekly draft PR with a diagnosed screen, cited problems, and a static mockup. Never merges itself.',
    href: 'https://github.com/Saikumar-bali/AAGAM_E-commerce/tree/main/automations/ux-redesign-proposals.json',
  },
  {
    id: 'sentry',
    name: 'Crash to issue',
    purpose: 'Puts every live failure on the team’s board automatically.',
    line: 'Sentry Issue Stream opens a tagged GitHub issue from a live production stack trace.',
    href: 'https://github.com/Saikumar-bali/AAGAM_E-commerce/issues?q=author%3Aapp%2Fsentry',
  },
]

export const automationStats = [
  { value: '40+', label: 'Workflows & agents' },
  { value: '8', label: 'Repos automated' },
  { value: '3', label: 'AI agents in prod' },
  { value: '4', label: 'GitHub achievements' },
]
