export const platforms = [
  {
    id: 'aws',
    name: 'AWS',
    proof: 'Hosts the HFT trading engine',
    icon: '/icons/aws.svg',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    proof: 'Workers, Pages, and R2 edge delivery',
    icon: 'https://cdn.simpleicons.org/cloudflare/242520',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    proof: 'Powers this portfolio and Vaji News',
    icon: 'https://cdn.simpleicons.org/vercel/242520',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    proof: 'Live public trading P&L dashboard',
    icon: 'https://cdn.simpleicons.org/grafana/242520',
  },
  {
    id: 'github-actions',
    name: 'GitHub Actions',
    proof: '40+ workflows across 8 repos',
    icon: 'https://cdn.simpleicons.org/githubactions/242520',
  },
  {
    id: 'docker',
    name: 'Docker',
    proof: 'Containerized CI and local stacks',
    icon: 'https://cdn.simpleicons.org/docker/242520',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    proof: 'Primary DB for AAGAM and Vaji',
    icon: 'https://cdn.simpleicons.org/postgresql/242520',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    proof: 'Realtime backend for HFT and apps',
    icon: 'https://cdn.simpleicons.org/supabase/242520',
  },
  {
    id: 'redis',
    name: 'Redis',
    proof: 'Session memory and CI service caches',
    icon: 'https://cdn.simpleicons.org/redis/242520',
  },
  {
    id: 'firebase',
    name: 'Firebase',
    proof: 'Stores hourly Telugu news harvests',
    icon: 'https://cdn.simpleicons.org/firebase/242520',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    proof: 'Turns production crashes into issues',
    icon: 'https://cdn.simpleicons.org/sentry/242520',
  },
  {
    id: 'playwright',
    name: 'Playwright',
    proof: 'E2E gates and attendance automation',
    icon: '/icons/playwright.svg',
  },
  {
    id: 'nextdotjs',
    name: 'Next.js',
    proof: 'Customer-facing apps in AAGAM',
    icon: 'https://cdn.simpleicons.org/nextdotjs/242520',
  },
  {
    id: 'nestdotjs',
    name: 'NestJS',
    proof: 'API gateway for the 3-app monorepo',
    icon: '/icons/nestjs.svg',
  },
  {
    id: 'react',
    name: 'React',
    proof: 'Default UI layer across the fleet',
    icon: 'https://cdn.simpleicons.org/react/242520',
  },
  {
    id: 'reactnative',
    name: 'React Native',
    proof: 'Movie Mandir and SMS Interceptor APKs',
    icon: 'https://cdn.simpleicons.org/react/242520',
  },
  {
    id: 'prisma',
    name: 'Prisma',
    proof: 'Type-safe ORM on PostgreSQL',
    icon: 'https://cdn.simpleicons.org/prisma/242520',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    proof: 'End-to-end type safety by default',
    icon: 'https://cdn.simpleicons.org/typescript/242520',
  },
  {
    id: 'nodedotjs',
    name: 'Node.js',
    proof: 'Runtime for bots, APIs, and the HFT engine',
    icon: 'https://cdn.simpleicons.org/nodedotjs/242520',
  },
  {
    id: 'python',
    name: 'Python',
    proof: 'ERP sniper and WhatsApp stealth bot',
    icon: 'https://cdn.simpleicons.org/python/242520',
  },
  {
    id: 'kotlin',
    name: 'Kotlin',
    proof: 'Native Android module in SMS Interceptor',
    icon: 'https://cdn.simpleicons.org/kotlin/242520',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    proof: 'Serverless scrape functions for news',
    icon: 'https://cdn.simpleicons.org/netlify/242520',
  },
  {
    id: 'render',
    name: 'Render',
    proof: 'Hosts several live client deploys',
    icon: 'https://cdn.simpleicons.org/render/242520',
  },
  {
    id: 'turbo',
    name: 'TurboRepo',
    proof: 'Monorepo builds for AAGAM 3-app suite',
    icon: 'https://cdn.simpleicons.org/turborepo/242520',
  },
]
