export const profile = {
  name: 'Saikumar Bali',
  title: 'Automation Architect & Full-Stack Engineer',
  tagline: 'I build systems that build themselves.',
    summary: 'Versatile Automation Architect and Full-Stack Engineer with 3+ years of independent delivery across fintech, AI integration, mobile development, DevOps, and cloud infrastructure. Architect of 20+ production systems, every claim verifiable via live URL, public repo, or shipped artifact.',
  location: 'Andhra Pradesh, India',
  email: 'saikumarbali55@gmail.com',
  phone: '+91 78422 04844',
  website: 'https://portfoliowebsite-ashen-two.vercel.app',
  github: 'https://github.com/saikumar-bali',
}

export const stats = [
  { value: '20+', label: 'Production systems shipped' },
  { value: '10+', label: 'Live deployments' },
  { value: '<500ms', label: 'Crash recovery' },
  { value: '3yr+', label: 'Independent delivery' },
]

export const featuredProjects = [
  {
    number: '01',
    name: 'High-Frequency Algo Trading Suite',
    type: 'Fintech · Quantitative Engineering',
    description: 'Production HFT engine executing multiple strategies across NSE, BSE, and MCX — with crash recovery, a live Grafana dashboard, and Telegram commands like /livepnl for on-the-go P&L.',
    metrics: ['Sub-500ms crash recovery', '3 concurrent strategies', 'Telegram /livepnl + live alerts', 'VaR-based position sizing'],
    stack: ['Node.js', 'WebSocket', 'Supabase', 'Grafana', 'Telegram Bot API', 'AWS'],
    links: { github: 'https://github.com/saikumar-bali/master_controller', live: 'https://saikumarbali55.grafana.net/public-dashboards/e7c3902f059b44128b326eb17fb2cf4d' },
    tone: 'planet',
    image: '/images/trading-bot/grafana.png',
    imageAlt: 'Grafana dashboard showing daily equity candles for the algo trading suite',
    overlay: { src: '/images/trading-bot/telegram.png', alt: 'Telegram bot replying to /livepnl with live open positions' },
    details: [
      {
        id: 'overview',
        title: 'Overview',
        kind: 'prose',
        intro: 'A production high-frequency trading engine that executes multiple concurrent strategies across NSE, BSE, and MCX. The system is built for resilience: crash recovery completes in under 500 ms, positions stream into a live Grafana dashboard, and a Telegram bot answers /livepnl for on-the-go P&L. Note: the source repository is private — the public proof is the live Grafana dashboard linked below.',
        metrics: ['Sub-500ms crash recovery', '3 concurrent strategies', 'Telegram /livepnl + live alerts', 'VaR-based position sizing'],
        meta: [
          { label: 'Live Dashboard', value: 'saikumarbali55.grafana.net (public)', href: 'https://saikumarbali55.grafana.net/public-dashboards/e7c3902f059b44128b326eb17fb2cf4d' },
          { label: 'Source Code', value: 'github.com/saikumar-bali/master_controller (private)', href: 'https://github.com/saikumar-bali/master_controller' },
          { label: 'Markets', value: 'NSE · BSE · MCX' },
        ],
      },
      {
        id: 'architecture',
        title: 'Architecture',
        kind: 'list',
        items: [
          { name: 'Master Controller', detail: 'Central orchestrator spawning and supervising one process per strategy with isolated state' },
          { name: 'Strategy Runtime', detail: 'Three concurrent strategies each own their signal loop, order router, and position book' },
          { name: 'Crash Recovery', detail: 'State persisted continuously so a killed process restores positions and resumes in under 500 ms' },
          { name: 'Market Data Feed', detail: 'WebSocket connections to broker endpoints streaming ticks into the signal layer' },
          { name: 'Risk Layer', detail: 'VaR-based position sizing gates every order before it reaches the broker' },
          { name: 'Telemetry', detail: 'Metrics exported to Grafana for equity curves, drawdown, and per-strategy P&L' },
          { name: 'Telegram Bot', detail: 'Command interface (/livepnl, live alerts) querying the position book in real time' },
        ],
      },
      {
        id: 'features',
        title: 'Features',
        kind: 'bullets',
        bullets: [
          'Multi-strategy execution across NSE, BSE, and MCX simultaneously',
          'Sub-500 ms crash recovery with full position restoration',
          'Live Grafana dashboard with daily equity candles (public link)',
          'Telegram /livepnl command plus push alerts on fills and drawdown',
          'VaR-based position sizing enforced before order submission',
          'Graceful degradation: strategies halt independently on feed loss',
        ],
      },
      {
        id: 'stack',
        title: 'Stack',
        kind: 'list',
        items: [
          { name: 'Node.js', detail: 'Event-loop runtime chosen for non-blocking market data handling' },
          { name: 'WebSocket', detail: 'Low-latency broker feed and order streaming' },
          { name: 'Supabase', detail: 'Persistent trade journal, strategy config, and recovery snapshots' },
          { name: 'Grafana', detail: 'Hosted dashboards for equity, drawdown, and live P&L' },
          { name: 'Telegram Bot API', detail: 'Command and alert channel' },
          { name: 'AWS', detail: 'Production host running the controller close to broker endpoints' },
        ],
      },
    ]
  },
  {
    number: '02',
    name: 'AAGAM E-Commerce Monorepo',
    type: 'Full-Stack · Architecture',
    description: 'Full-featured e-commerce platform with three synchronized client applications — Admin, Customer, and Rider — sharing a single backend and state machine.',
    metrics: ['3 client apps in 1 monorepo', 'Socket.io real-time sync', 'E2E TypeScript type safety', 'Finite state machine order lifecycle'],
    stack: ['TypeScript', 'Next.js', 'NestJS', 'React Native', 'Socket.io', 'Prisma', 'PostgreSQL'],
    links: { github: 'https://github.com/saikumar-bali/AAGAM_E-commerce', live: 'https://aagaam.in' },
    tone: 'paper',
    image: '/images/aagaam/aagaam.png',
    imageAlt: 'AAGAM customer shop with subscribe-and-save plans',
    gallery: [
      { src: '/images/aagaam/aagam_store.png', alt: 'Store owner subscription runs 31-day matrix' },
      { src: '/images/aagaam/aagam_mobile2.png', alt: 'AAGAM mobile subscription review screen' },
    ],
    details: [
      {
        id: 'overview',
        title: 'Overview',
        kind: 'prose',
        intro: 'AAGAM is a production-grade e-commerce monorepo: an npm-workspaces + Turborepo workspace holding 5 apps and 6 shared packages behind a single NestJS backend. Three client apps — Admin, Customer, and Rider/Partners — share one database, one state machine, and one real-time layer. The admin dashboard alone compiles 51 pages, and the repo carries 60+ architecture documents alongside a fully automated deploy pipeline.',
        metrics: ['5 apps · 6 packages', '51 compiled admin pages', '60+ architecture docs', '163 MB repo · 700+ dependencies'],
        meta: [
          { label: 'Deployment', value: 'AWS EC2 · nginx · PM2 · PostgreSQL 18 · Port 3005/3001' },
          { label: 'Live Site', value: 'aagaam.in', href: 'https://aagaam.in' },
          { label: 'Source Code', value: 'github.com/Saikumar-bali/AAGAM_E-commerce', href: 'https://github.com/Saikumar-bali/AAGAM_E-commerce' },
        ],
      },
      {
        id: 'architecture',
        title: 'Architecture',
        kind: 'list',
        items: [
          { name: 'Turborepo Monorepo', detail: 'npm workspaces orchestrated by Turborepo ^2.10.7 with task caching and parallel builds across all 5 apps' },
          { name: 'Single API Gateway', detail: 'apps/api-gateway (NestJS 11.1.28) owns all business logic, Socket.io real-time events, and the test suites' },
          { name: 'Shared Packages', detail: '@aagam/types, @aagam/utils, @aagam/database, @aagam/ui, mobile-shared — one source of truth for all clients' },
          { name: 'Derived Subscription Ledger', detail: 'reconcileSubscriptionBalance() treats the ledger as a floor and absorbs day-cell cash drift across the 31-day matrix' },
          { name: 'Idempotent SQL Migrations', detail: 'ADD COLUMN IF NOT EXISTS / CREATE INDEX IF NOT EXISTS / DO $$ exception blocks so prisma migrate deploy survives manually-applied DDL' },
          { name: 'Finite State Machine', detail: 'Centralized order lifecycle: PLACED → CONFIRMED → PROCESSING → SHIPPED → DELIVERED → RETURNED' },
          { name: 'Outbox & Domain Docs', detail: 'docs/ carries NOTIFICATION_OUTBOX_ARCHITECTURE.md, DELIVERY_DOMAIN_STATE_MACHINE.md, PARTNER_ONBOARDING_ARCHITECTURE.md and 60+ phase docs' },
        ],
      },
      {
        id: 'backend',
        title: 'Backend',
        kind: 'list',
        items: [
          { name: 'NestJS 11.1.28 Gateway', detail: 'Centralized API handling all microservice communication, authentication, and routing for the 3 client apps on port 3005' },
          { name: 'Prisma 5.22.0', detail: 'Type-safe ORM with end-to-end TypeScript safety from database to UI layer' },
          { name: 'PostgreSQL 18', detail: 'Primary database on port 5432 (DB aagam_ecom) with connection pooling; CI runs postgres:15-alpine on 5433' },
          { name: 'Socket.io Real-Time', detail: 'Bidirectional events syncing orders, delivery tracking, and inventory across all clients simultaneously' },
          { name: 'Worker Service', detail: 'apps/worker-service runs background jobs off the request path' },
          { name: 'JWT Auth', detail: 'Token-based authentication with refresh tokens, protected routes, and role-based access control' },
          { name: 'PM2 Runtime', detail: 'ecosystem.config.js + ensure-pm2-node22-runtime.sh keep the Node 22 process supervised in production' },
        ],
      },
      {
        id: 'apps',
        title: 'Applications',
        kind: 'apps',
        apps: [
          { name: 'Admin Dashboard', stack: ['Next.js 14.1.0', 'React 19', 'Tailwind CSS', 'TypeScript'], description: '51 compiled pages covering the entire operation — orders, catalog, customers, analytics, inventory, and role management.', features: ['Order dashboard & analytics', 'Product catalog management', 'Customer management', 'Inventory control', 'User role management'] },
          { name: 'Customer Store', stack: ['Next.js 14.1.0', 'React 19', 'Tailwind CSS'], description: 'Storefront with subscribe-and-save plans driven by the 31-day matrix pricing model.', features: ['Product browsing & cart', 'Checkout flow', 'Subscribe & save plans', 'Order tracking', 'Reviews & ratings'] },
          { name: 'Mobile Apps (Expo)', stack: ['Expo', 'React Native', 'react-native-dotenv'], description: 'mobile-customer and mobile-partners share packages/mobile-shared and ship through the android-apk-release workflow.', features: ['Customer ordering', 'Partner/Rider delivery flow', 'Shared mobile package', 'Maestro E2E coverage'] },
        ],
      },
      {
        id: 'testing',
        title: 'Testing',
        kind: 'bullets',
        bullets: [
          'Jest phase suites 6–12 plus ETA lifecycle simulation',
          'Maestro mobile E2E for customer/ and partners/ flows',
          'k6 + Artillery load tests: API, checkout, rider WebSocket throughput, campaigns',
          'Lighthouse CI performance budgets',
          'Playwright ^1.61.1 for inventory, promotions, partner, and rider E2E',
          'Security hardening: patch-image-size-cves.js, dependency-security-audit.yml, verify-dependency-security.js',
          '7 seeded test accounts and a CI health check with 60s API window + 2s stabilization',
        ],
      },
      {
        id: 'deployment',
        title: 'Deployment',
        kind: 'list',
        items: [
          { name: 'CI → Deploy production', detail: 'workflow_run pipeline gated on CI success, concurrency group production-deploy, 45-minute job timeout' },
          { name: 'SSH Deploy with Guard Rails', detail: 'Refuses commits not contained in origin/main, validates port ranges, rejects DEPLOY_PATH of /, /home, /root, /opt, /var, /usr' },
          { name: 'Exact-Revision Proof', detail: '30 × 5 s poll of the frontend and /api/health asserting status ok AND revision === DEPLOY_SHA' },
          { name: 'Injected Secrets', detail: 'Firebase service account, WhatsApp Business Graph, Mapbox + Google Maps tokens, validated by validate-prod-env.js' },
          { name: 'Other Workflows', detail: 'ci.yml, android-apk-release.yml, dependency-security-audit.yml, trigger-coderabbit.yml' },
        ],
      },
      {
        id: 'stack',
        title: 'Stack',
        kind: 'list',
        items: [
          { name: 'Turborepo ^2.10.7 + npm 11.6.1', detail: 'Monorepo orchestration with task caching and parallel builds' },
          { name: 'NestJS 11.1.28 + Socket.io', detail: 'Backend framework pinned via package.json overrides' },
          { name: 'Next.js 14.1.0 + React 19', detail: 'Web frontends with Tailwind CSS' },
          { name: 'Prisma 5.22.0 + PostgreSQL 18', detail: 'Type-safe data layer' },
          { name: 'mapbox-gl ^3.29.0', detail: 'Maps with Google Maps keys wired in deploy' },
          { name: 'Node 22.22.3 (CI) / PM2', detail: 'Production runtime, TypeScript strict mode throughout' },
        ],
      },
    ]
  },
  {
    number: '03',
    name: 'Movie Mandir — SDUI Streaming',
    type: 'React Native · DevOps',
    description: 'React Native CLI streaming app whose entire UI is driven by a remote JSON schema — Server-Driven UI — allowing UI changes without app releases.',
    metrics: ['Sub-150ms UI latency', 'Custom SDUI engine', 'Automated APK CI/CD', 'Shipped production APK v1.0.1'],
    stack: ['React Native CLI', 'TypeScript', 'Supabase Realtime', 'Cloudinary', 'GitHub Actions'],
    links: { github: 'https://github.com/Saikumar-bali/movie_mandir', apk: 'https://github.com/Saikumar-bali/movie_mandir/releases/download/v1.0.1/movie_mandir_v1.0.1.apk' },
    tone: 'garden',
    details: [
      {
        id: 'overview',
        title: 'Overview',
        kind: 'prose',
        intro: 'Movie Mandir is a React Native streaming app whose hidden admin surface is entirely Server-Driven UI: the "Secret Channel" layout lives as a JSON row in a Supabase app_config table, so re-skins ship without an app release. Content is passcode-locked, media is served through Cloudinary transformations, and support chat runs on Supabase Realtime.',
        metrics: ['React Native 0.82.0 · React 19.1.1', 'SDUI layout stored as JSON in Postgres', 'Auto-built Release APK on every main push', 'Supabase Realtime support chat'],
        meta: [
          { label: 'Source Code', value: 'github.com/Saikumar-bali/movie_mandir', href: 'https://github.com/Saikumar-bali/movie_mandir' },
          { label: 'Download', value: 'APK v1.0.1 (GitHub Releases)', href: 'https://github.com/Saikumar-bali/movie_mandir/releases/download/v1.0.1/movie_mandir_v1.0.1.apk' },
          { label: 'Backend', value: 'Supabase (PostgreSQL + Realtime) · Cloudinary' },
        ],
      },
      {
        id: 'sdui',
        title: 'Server-Driven UI',
        kind: 'list',
        items: [
          { name: 'Secret Channel', detail: 'Hidden dashboard opened by a long-press on the header — never visible in normal navigation' },
          { name: 'JSON Layout Engine', detail: 'The whole screen is one row in app_config.layout; the renderer walks type: text / slider / chat nodes' },
          { name: 'Instant Re-Skin', detail: 'Updating the JSON row changes the screen on next fetch — no Play Store release required' },
          { name: 'Passcode Lock', detail: 'Images and videos inside the secret channel require a passcode before they resolve' },
          { name: 'Realtime Admin Chat', detail: 'support_messages table with Supabase Realtime powers live support inside the app' },
        ],
      },
      {
        id: 'features',
        title: 'Features',
        kind: 'bullets',
        bullets: [
          'Video streaming via react-native-video ^6.18.0 with category filtering',
          'Deep detail screens for Movies and Series',
          'Cloudinary dynamic transformations for high-performance media delivery',
          'Real-time support chat with admins (Supabase Realtime)',
          'Background fetch, orientation locking, and netinfo-driven offline states',
          'Jest + react-test-renderer coverage with ESLint and Prettier',
        ],
      },
      {
        id: 'stack',
        title: 'Stack',
        kind: 'list',
        items: [
          { name: 'React Native 0.82.0 + React 19.1.1', detail: 'TypeScript ^5.8.3, Node >=20' },
          { name: 'supabase-js ^2.93.3', detail: 'PostgreSQL + Realtime; tables app_config and support_messages' },
          { name: 'Cloudinary', detail: 'Media storage and on-the-fly transformations' },
          { name: 'React Navigation ^7', detail: 'Stack navigation with gesture handler and Reanimated ^4.2.0' },
          { name: 'react-native-video ^6.18.0', detail: 'Playback engine with slider controls (3000 ms auto-advance)' },
          { name: 'Axios ^1.13.2', detail: 'HTTP layer with async-storage persistence' },
        ],
      },
      {
        id: 'deployment',
        title: 'Deployment',
        kind: 'bullets',
        bullets: [
          'GitHub Action android-build.yml attempts an unsigned Release APK on every push to main',
          'Artifacts land in the Actions tab; Play Store signing needs Android Signing Secrets',
          'Manual build: cd android && ./gradlew assembleRelease',
          'DB bootstrap: run supabase_setup.sql in the Supabase SQL Editor (creates tables + enables Realtime)',
          'Env: copy src/config/env.example.js → env.js with SUPABASE_URL and SUPABASE_ANON_KEY',
        ],
      },
    ]
  },
  {
    number: '04',
    name: 'ERP Precision Automation',
    type: 'Automation · Cloud',
    description: 'Dual-layer automation system that reliably marks attendance at millisecond precision — with geolocation spoofing and redundant fallback.',
    metrics: ['10:00:00.005 precision', 'Dual-layer redundancy', 'CF Workers primary', 'Playwright fallback'],
    stack: ['Cloudflare Workers', 'Playwright', 'Python', 'GitHub Actions', 'Node.js'],
    links: { github: 'https://github.com/saikumar-bali/erp_automation_bot' },
    tone: 'planet',
    image: '/images/attendance-bot/image.png',
    imageAlt: 'Attendance Bot dashboard with May 2026 calendar of marked days and execution success logs',
    details: [
      {
        id: 'overview',
        title: 'Overview',
        kind: 'prose',
        intro: 'Hippo ERP Bot is a precision attendance automation suite with a dual-layer architecture: Cloudflare Workers as the ultra-fast primary engine and GitHub Actions + Playwright as the browser-based failover. The "Precision Sniper" strategy aims for an exact 10:00:00.000 punch by pre-warming one minute early, with a glassmorphic dashboard, holiday awareness, and geolocation spoofing.',
        metrics: ['Millisecond-level punch accuracy', 'Dual-layer redundancy', 'Cloudflare Workers primary', 'Playwright fallback'],
        meta: [
          { label: 'Source Code', value: 'github.com/Saikumar-bali/erp_automation_bot', href: 'https://github.com/Saikumar-bali/erp_automation_bot' },
          { label: 'Primary Layer', value: 'Cloudflare Workers (serverless REST)' },
          { label: 'Backup Layer', value: 'GitHub Actions + Playwright (headless Chromium)' },
        ],
      },
      {
        id: 'architecture',
        title: 'Architecture',
        kind: 'list',
        items: [
          { name: 'Cloudflare Worker (Primary)', detail: 'Direct REST API interaction with no browser overhead — the "Precision Sniper" path' },
          { name: 'Pre-Warm Logic', detail: 'Cron fires one minute early (29 4 * * MON-SAT) to pre-authenticate and eliminate login latency' },
          { name: 'GitHub Actions Failover', detail: 'Python + Playwright on headless Chromium when the API is restricted or screenshots are needed' },
          { name: 'Built-in Dashboard', detail: 'Glassmorphic web UI to toggle WORK / LEAVE modes, view calendar and execution logs' },
          { name: 'Geolocation Spoofing', detail: 'Coordinates injected to satisfy the ERP location requirement' },
          { name: 'Smart Scheduling', detail: 'Always fires on IST regardless of server location; syncs the ERP holiday list' },
        ],
      },
      {
        id: 'features',
        title: 'Features',
        kind: 'bullets',
        bullets: [
          'Precision Sniper hits the punch target within milliseconds of schedule (logged as 10:00:00.005)',
          'Multi-user support processes several employee accounts in parallel',
          'Holiday awareness auto-syncs with the ERP holiday list',
          'Millisecond-level execution logs for audit evidence',
          'Two GitHub Actions workflows: scheduled-attendance.yml and erp-task-sync.yml',
          'Secrets managed through GitHub repository secrets / wrangler secret',
        ],
      },
      {
        id: 'stack',
        title: 'Stack',
        kind: 'list',
        items: [
          { name: 'Cloudflare Workers', detail: 'worker.js + attendance.js primary layer with wrangler.toml KV config' },
          { name: 'Python', detail: 'src/auto_attendance.py automation core and check_logs.py' },
          { name: 'Playwright', detail: 'Headless Chromium browser automation for the failover layer' },
          { name: 'GitHub Actions', detail: 'Scheduled runs with secure secret management' },
          { name: 'Node.js Tooling', detail: 'package.json scripts and local attendance.js (Puppeteer) variant' },
        ],
      },
      {
        id: 'deployment',
        title: 'Deployment',
        kind: 'bullets',
        bullets: [
          'Deploy Worker: npx wrangler deploy with KV namespace bound',
          'Cron triggers: 29 4 * * MON-SAT (09:59 IST) and 29 13 * * MON-SAT (18:59 IST)',
          'Secrets: CONFIG (credentials + coordinates) and DASHBOARD_PWD via wrangler secret',
          'Secondary layer: fork repo, add ERP_USERNAME / ERP_PASSWORD / LATITUDE / LONGITUDE secrets, enable workflow',
          'Monitoring: https://your-worker.workers.dev/?pwd=YOUR_PWD shows calendar and logs',
        ],
      },
    ]
  },
  {
    number: '05',
    name: 'WhatsApp AI Automation Bot',
    type: 'AI Integration · Automation',
    description: 'Stealth-mode WhatsApp automation bot that reads incoming messages and replies via LLM, while evading anti-bot detection.',
    metrics: ['Stealth mode operation', 'Groq/Llama 3 LLM', 'Persistent browser sessions', 'Human-like interaction patterns'],
    stack: ['Python', 'Groq AI', 'Selenium', 'Llama 3'],
    links: { github: 'https://github.com/saikumar-bali/whatsapp-ai-automation' },
    tone: 'paper',
    details: [
      {
        id: 'overview',
        title: 'Overview',
        kind: 'prose',
        intro: 'GrokWA-Auto v2.0 reads incoming WhatsApp Web messages and replies through a Groq LLM while imitating a real person: 60 words-per-minute typing, a deliberate 4% typo rate with corrections, circadian activity rhythms, and 2–10 second response delays. A local Ollama model takes over when the cloud key is unavailable, and a FastAPI dashboard streams live logs.',
        metrics: ['GrokWA-Auto v2.0', 'llama-3.3-70b + Ollama fallback', '60 WPM · 4% typo rate · circadian rhythm', 'FastAPI dashboard on :8085'],
        meta: [
          { label: 'Source Code', value: 'github.com/Saikumar-bali/whatsapp-ai-automation', href: 'https://github.com/Saikumar-bali/whatsapp-ai-automation' },
          { label: 'Language', value: 'Python 3.8+' },
          { label: 'Dashboard', value: 'http://localhost:8085 (live logs)' },
        ],
      },
      {
        id: 'architecture',
        title: 'Architecture',
        kind: 'list',
        items: [
          { name: 'main.py', detail: 'Entry point: boots the automation loop and the FastAPI server together' },
          { name: 'ai_engine.py', detail: 'Groq model interactions with an Ollama localhost:11434 fallback (fallback_enabled: true)' },
          { name: 'whatsapp_client.py', detail: 'Selenium session driving WhatsApp Web, reading inbound and sending outbound messages' },
          { name: 'humanizer.py', detail: 'Typing-speed simulation, typo injection with corrections, circadian delay shaping' },
          { name: 'find_profiles.py', detail: 'Profile discovery helper for target threads' },
          { name: 'Session Memory', detail: 'chroma_db vector store + sqlite:///./app.db for long-term conversation context' },
          { name: 'config.yaml', detail: 'Central tuning surface: app, browser, ai, humanizer, memory sections' },
        ],
      },
      {
        id: 'stealth',
        title: 'Stealth Mode',
        kind: 'list',
        items: [
          { name: 'Typing Cadence', detail: '60 WPM simulated keystrokes instead of instant paste' },
          { name: 'Typo Rate 4%', detail: 'Occasional typos followed by human-style corrections' },
          { name: 'Circadian Rhythm', detail: 'Activity windows modelled on day/night behaviour' },
          { name: 'Response Delay 2–10 s', detail: 'Random think-time before each reply' },
          { name: 'Session Persistence', detail: 'user_data/ keeps the WhatsApp Web login so the QR is scanned once' },
          { name: 'Tanglish Persona', detail: 'System prompt enforces casual lowercase Tanglish (Telugu words in Latin script)' },
        ],
      },
      {
        id: 'stack',
        title: 'Stack',
        kind: 'list',
        items: [
          { name: 'Groq · llama-3.3-70b-versatile', detail: 'Primary cloud inference for reply generation' },
          { name: 'Ollama · mistral', detail: 'Local fallback at localhost:11434 when the key is unavailable' },
          { name: 'Selenium + webdriver-manager', detail: 'Chrome automation with persistent user_data dir' },
          { name: 'FastAPI', detail: 'Dashboard with status and live log streaming on port 8085' },
          { name: 'loguru · beautifulsoup4 · pyyaml', detail: 'Logging, parsing, and YAML configuration' },
        ],
      },
      {
        id: 'deployment',
        title: 'Deployment',
        kind: 'bullets',
        bullets: [
          'python -m venv venv → pip install -r requirements.txt (setup.sh included)',
          'Set GROK_API_KEY from console.groq.com and LOG_LEVEL=INFO in .env',
          'python main.py launches Chrome (headless: false for the first QR scan)',
          'Tune model, humanizer, and browser behaviour in config.yaml',
          'No CI workflows — runs as a local long-lived process',
        ],
      },
    ]
  },
]

export const additionalProjects = [
  { name: 'ReelGenius AI', description: 'Browser-side AI video creator — Gemini Flash generates timestamps, Web Audio syncs, Canvas renders MP4. Zero server.', tech: ['React', 'Gemini AI', 'Web Audio', 'Canvas API'], links: { github: 'https://github.com/saikumar-bali/reel_genius_ai', live: 'https://reel-genius-ai.onrender.com' } },
  { name: 'HippoClouds Website', description: 'Enterprise SaaS portal for CRM/HRM/Mint with AI lead-qualification chatbot and CRM webhook integration.', tech: ['React', 'Framer Motion'], links: { live: 'https://hippoclouds-website.onrender.com' } },
  { name: 'JY Defence Academy', description: 'Educational portal with military HUD aesthetic, custom SVG radar components, TanStack Router.', tech: ['React', 'TypeScript'], links: { live: 'https://jy-defence-acadamy.onrender.com' } },
  { name: 'CineVerse PWA', description: 'Movie/series discovery PWA with custom stream broker solving provider-side CORS restrictions.', tech: ['React', 'Supabase'], links: { live: 'https://cine-verse-v3fs.onrender.com' } },
  { name: 'Patala Pustakam', description: 'Hybrid-backend e-commerce — Express for orders, Cloudflare Workers for edge catalog delivery.', tech: ['Next.js', 'CF Workers'], links: { live: 'https://patala-pusthakam.onrender.com' } },
  { name: 'Telugu News Aggregator', description: 'Serverless pipeline scraping 20+ Telugu news sources via Netlify Functions + GitHub Actions cron.', tech: ['Svelte', 'Firebase'], links: { live: 'https://news-website-2ev.pages.dev/' } },
  { name: 'Vaji News Platform', description: 'Next.js SSR aggregator with Prisma/PostgreSQL and automated dedup via content hashing.', tech: ['Next.js', 'Prisma'], links: { live: 'https://vaji-news.vercel.app' } },
  { name: 'HippoCloud Elevate 3D', description: 'Enterprise WebGL portal with bloom/SSAO post-processing, LOD system, automated GLTF compression.', tech: ['Three.js', 'R3F'], links: { github: 'https://github.com/saikumar-bali/hippocloud-elevate' } },
  { name: 'Bill Tracker', description: 'Real-time expense tracker with WebSocket live updates + automated recurring payment detection.', tech: ['React', 'Node.js'], links: { live: 'https://bill-tracker.saikumarbali555.workers.dev/' } },
  { name: 'AI Customer Support Bot', description: 'GPT-powered chatbot with Redis-backed session memory for long-term context + intelligent escalation.', tech: ['Node.js', 'GPT', 'Redis'], links: { github: 'https://github.com/saikumar-bali/chat_bot' } },
]

export const skills = {
  'Languages': ['TypeScript', 'JavaScript', 'Python', 'Kotlin', 'HTML/CSS', 'SQL'],
  'Frontend': ['React', 'Next.js', 'Svelte', 'Tailwind CSS', 'shadcn/ui', 'Framer Motion', 'Three.js / R3F', 'Canvas API', 'Web Audio API'],
  'Mobile': ['React Native CLI', 'Kotlin', 'Broadcast Receivers', 'SDUI Architecture'],
  'Backend': ['Node.js', 'NestJS', 'Express', 'Prisma ORM', 'Socket.io', 'WebSocket', 'REST', 'Cloudflare Workers'],
  'AI / LLM': ['Gemini AI', 'Groq / Llama 3', 'OpenAI GPT', 'Prompt Engineering', 'LLM Session Memory'],
  'DevOps & Cloud': ['Docker', 'AWS', 'Cloudflare', 'Vercel', 'Netlify', 'Grafana', 'TurboRepo', 'GitHub Actions'],
  'Databases': ['PostgreSQL', 'Supabase', 'Redis', 'Firebase', 'Cloudinary'],
  'Architecture': ['Monorepo Design', 'Server-Driven UI', 'Finite State Machines', 'Edge + Origin Hybrid', 'Dual-Layer Failover', 'Event-Driven Systems'],
}

export const navigation = [
  { id: 'home', label: 'Home' },
  { id: 'work', label: 'Work' },
  { id: 'automation', label: 'Automation' },
  { id: 'about', label: 'About' },
  { id: 'contact', label: 'Contact' },
]
